H-R-WS/Controllers/BookingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using H_R_WS.Data;
using H_R_WS.Models;
using H_R_WS.Services;

namespace H_R_WS.Controllers
{
    public class BookingsController : Controller
    {
        private readonly IGenericHotelService<Booking> _hotelService;

        public BookingsController(IGenericHotelService<Booking> genericHotelService)
        {
            _hotelService = genericHotelService;
        }

        // GET: Bookings
        public async Task<IActionResult> Index()
        {
            return View(await _hotelService.GetAllItemsAsync());
        }

        // GET: Bookings/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var booking = await _hotelService.GetItemByIdAsync(id);


            if (booking == null)
            {
                return NotFound();
            }


            return View(booking);
        }

            // GET: Bookings/Create
            public IActionResult Create()
        {
            return View();
        }

        // POST: Bookings/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,RoomID,DateCreated,CheckIn,CheckOut,Guests,TotalFee,Paid,Completed,ApplicationUserId,CustomerName,CustomerEmail,CustomerPhone,CustomerAddress,CustomerCity,OtherRequests")] Booking booking)
        {
            if (ModelState.IsValid)
            {
                booking.ID = Guid.NewGuid().ToString();
                await _hotelService.CreateItemAsync(booking);
                return RedirectToAction(nameof(Index));
            }
            return View(booking);
        }

        // GET: Bookings/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var booking = await _hotelService.GetItemByIdAsync(id);

            var rooms = _hotelService.GetAllRoomsWithFeature(id);
            ViewData["RoomsWithFeature"] = rooms;
            if (booking == null)
            {
                return NotFound();
            }
            return View(booking);
        }

        // POST: Bookings/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("ID,RoomID,DateCreated,CheckIn,CheckOut,Guests,TotalFee,Paid,Completed,ApplicationUserId,CustomerName,CustomerEmail,CustomerPhone,CustomerAddress,CustomerCity,OtherRequests")] Booking booking)
        {
            if (id != booking.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _hotelService.EditItemAsync(booking);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (_hotelService.GetItemByIdAsync(id) == null)
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(booking);
        }

        // GET: Bookings/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var booking = await _hotelService.GetItemByIdAsync(id);
            if (booking == null)
            {
                return NotFound();
            }

            return View(booking);
        }

        // POST: Bookings/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var booking = await _hotelService.GetItemByIdAsync(id);
            await _hotelService.DeleteItemAsync(booking);
            return RedirectToAction(nameof(Index));
        }

    }
}

H-R-WS/Controllers/RoomTypesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using H_R_WS.Data;
using H_R_WS.Models;
using H_R_WS.Services;
using Microsoft.AspNetCore.Authorization;

namespace H_R_WS.Controllers
{
    [Authorize]
    public class RoomTypesController : Controller
    {
        private readonly IGenericHotelService<RoomType> _hotelService;

        public RoomTypesController(IGenericHotelService<RoomType> genericHotelService)
        {
            _hotelService = genericHotelService;
        }

        // GET: RoomTypes
        public async Task<IActionResult> Index()
        {
            return View(await _hotelService.GetAllItemsAsync());
        }

        // GET: RoomTypes/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var roomType = await _hotelService.GetItemByIdAsync(id);


            if (roomType == null)
            {
                return NotFound();
            }

            var rooms = _hotelService.GetAllRooms().Where(x => x.RoomTypeID == id);
            ViewData["CategoryRooms"] = rooms;
            return View(roomType);
        }

        // GET: RoomTypes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: RoomTypes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,BasePrice,Description,ImageUrl")] RoomType roomType)
        {
            if (ModelState.IsValid)
            {
                roomType.ID = Guid.NewGuid().ToString();
                await _hotelService.CreateItemAsync(roomType);
                return RedirectToAction(nameof(Index));
            }
            return View(roomType);
        }

        // GET: RoomTypes/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var roomType = await _hotelService.GetItemByIdAsync(id);
            if (roomType == null)
            {
                return NotFound();
            }
            return View(roomType);
        }

        // POST: RoomTypes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("ID,Name,BasePrice,Description,ImageUrl")] RoomType roomType)
        {
            if (id != roomType.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _hotelService.EditItemAsync(roomType);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (_hotelService.GetItemByIdAsync(id) == null)
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(roomType);
        }

        // GET: RoomTypes/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var roomType = await _hotelService.GetItemByIdAsync(id);
            if (roomType == null)
            {
                return NotFound();
            }

            return View(roomType);
        }

        // POST: RoomTypes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var roomType = await _hotelService.GetItemByIdAsync(id);
            await _hotelService.DeleteItemAsync(roomType);
            return RedirectToAction(nameof(Index));
        }
    }
}

H-R-WS/Controllers/RoomsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using H_R_WS.Data;
using H_R_WS.Models;
using H_R_WS.Services;
using Microsoft.AspNetCore.Authorization;

namespace H_R_WS.Controllers
{
    [Authorize]
    public class RoomsController : Controller
    {
        private readonly IGenericHotelService<Room> _RoomService;

        public RoomsController(IGenericHotelService<Room> genericHotelService)
        {
            _RoomService = genericHotelService;
        }

        // GET: Rooms
        public IActionResult Index()
        {
            return View(_RoomService.GetAllRoomsAndRoomTypes());
        }
        // GET: Rooms/Details/5
        public async Task<IActionResult> Details(string id)
        {
            var room = _RoomService.GetAllRooms().SingleOrDefault(x => x.ID == id);

            if (room == null)
            {
                return NotFound();
            }

            var ImagesAndFeatures = await _RoomService.GetRoomFeaturesAndImagesAsync(room);
            ViewData["Features"] = ImagesAndFeatures.Features;
            ViewData["Images"] = ImagesAndFeatures.Images;
            return View(room);
        }

        // GET: Rooms/Create
        public IActionResult Create()
        {
            var Room = _RoomService.GetAllRoomTypesAsync().Result;
            ViewData["RoomTypeID"] = new SelectList(Room, "ID", "Name");
            var room = new Room();
            ViewData["Features"] = _RoomService.PopulateSelectedFeaturesForRoom(room);
            return View();
        }

        // POST: Rooms/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Number,RoomTypeID,Price,Available,Description,MaximumGuests")] Room room, string[] SelectedFeatureIDs, string[] imageIDs)
        {
            if (ModelState.IsValid)
            {
                room.ID = Guid.NewGuid().ToString();
                await _RoomService.CreateItemAsync(room);
                _RoomService.UpdateRoomFeaturesList(room, SelectedFeatureIDs);
                _RoomService.UpdateRoomImagesList(room, imageIDs);
                return RedirectToAction(nameof(Index));
            }
            ViewData["Features"] = _RoomService.PopulateSelectedFeaturesForRoom(room);
            var ImagesAndFeatures = await _RoomService.GetRoomFeaturesAndImagesAsync(room);
            ViewData["Images"] = ImagesAndFeatures.Images;
            return View(room);
        }

        // GET: Rooms/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var room = await _RoomService.GetItemByIdAsync(id);
            if (room == null)
            {
                return NotFound();
            }
            var RoomTypes = _RoomService.GetAllRoomTypesAsync().Result;
            ViewData["RoomTypeID"] = new SelectList(RoomTypes, "ID", "Name", room.RoomType.ID);

            ViewData["Features"] = _RoomService.PopulateSelectedFeaturesForRoom(room);
            var ImagesAndFeatures = await _RoomService.GetRoomFeaturesAndImagesAsync(room);
            ViewData["Images"] = ImagesAndFeatures.Images;
            return View(room);
        }

        // POST: Rooms/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("ID,Number,RoomTypeID,Price,Available,Description,MaximumGuests")] Room room, string[] SelectedFeatureIDs, string[] imageIDs)
        {
            if (id != room.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _RoomService.EditItemAsync(room);
                    _RoomService.UpdateRoomFeaturesList(room, SelectedFeatureIDs);
                    _RoomService.UpdateRoomImagesList(room, imageIDs);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (_RoomService.GetItemByIdAsync(id) == null)
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            var RoomTypes = _RoomService.GetAllRoomTypesAsync().Result;
            ViewData["RoomTypeID"] = new SelectList(RoomTypes, "ID", "ID", room.RoomTypeID);
            ViewData["Features"] = _RoomService.PopulateSelectedFeaturesForRoom(room);
            var ImagesAndFeatures = await _RoomService.GetRoomFeaturesAndImagesAsync(room);
            ViewData["Images"] = ImagesAndFeatures.Images;
            return View(room);
        }

        // GET: Rooms/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var room = await _RoomService.GetItemByIdAsync(id);
            if (room == null)
            {
                return NotFound();
            }

            return View(room);
        }

        // POST: Rooms/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var room = await _RoomService.GetItemByIdAsync(id);
            await _RoomService.DeleteItemAsync(room);
            return RedirectToAction(nameof(Index));
        }
        /*
        private bool RoomExists(Guid id)
        {
            return _RoomService.Rooms.Any(e => e.ID == id);
        }
        */
    }
}

H-R-WS/Views/Shared/GetAllImagesPartial.cshtml
@model IEnumerable<H_R_WS.Models.Image>

<div class="row">
    @foreach (var item in Model)
    {
        <div class="col-md-3 panel">
            <div style="background-color:lightgrey; margin:2px;" class="imageItem" id="@item.ID">
                <div>
                    <input type="checkbox" name="selectedImages" value="@item.ID" data-url="@item.ImageUrl" style="float:left;" />
                    <img class="img-responsive" src="@item.ImageUrl" asp-append-version="true" alt="@item.Name" width="200" />
                    <div class="panel-group" style="padding:5px;">
                        <p>@item.Name</p>
                    </div>
                </div>
            </div>
        </div>
    }
</div> 

H-R-WS/Views/Shared/_Layout.cshtml
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Система управління готелем - це програмне забезпечення для управління готелем.">
    <title>Тестовий готель</title>
    <!-- ========== Файли Css ========== -->
    <link href="~/css/root.css" rel="stylesheet">
</head>
<body>
    <!-- Початок завантаження сторінки -->
    <div class="loading"><img src="~/img/loading.gif" alt="loading-img"></div>
    <!-- Кінець завантаження сторінки -->
    <!-- //////////////////////////////////////////////////////////////////////////// -->
    <!-- Верхня частина початок -->
    <div id="top" class="clearfix">
        <!-- Початок лого -->
        <div class="applogo">
            <a href="index.html" class="logo">Тестовий Готель</a>
        </div>
        <!-- Кінець лого -->
        <!-- Сайдбар початок -->
        <a href="#" class="sidebar-open-button"><i class="fa fa-bars"></i></a>
        <a href="#" class="sidebar-open-button-mobile"><i class="fa fa-bars"></i></a>
        <!-- Сайдбар Кінець -->
        <!-- Поле пошуку початок -->
        <form class="searchform">
            <input type="text" class="searchbox" id="searchbox" placeholder="Пошук">
            <span class="searchbutton"><i class="fa fa-search"></i></span>
        </form>
        <!-- Поле пошуку кінець -->
        <!-- Сайдпанель початок -->
        <a href="#sidepanel" class="sidepanel-open-button"><i class="fa fa-outdent"></i></a>
        <!-- Сайдпанель кінець -->
        <!-- Верхня права ч. початок -->
        <ul class="top-right">
            <li class="dropdown link">
                <a href="#" data-toggle="dropdown" class="dropdown-toggle hdbutton">Створити нове <span class="caret"></span></a>
                <ul class="dropdown-menu dropdown-menu-list">
                    <li><a asp-action="Create" asp-controller="Rooms"><i class="fa falist fa-bed"></i>Кімната</a></li>
                    <li><a asp-action="Create" asp-controller="RoomTypes"><i class="fa falist fa-folder-open"></i>Категорія Кімнати</a></li>
                    <li><a asp-action="Create" asp-controller="Features"><i class="fa falist fa-check-square-o"></i>Особливості</a></li>
                    <li><a asp-action="Create" asp-controller="Bookings"><i class="fa falist fa-calendar"></i>Бронювання</a></li>
                </ul>
            </li>
            <form asp-area="" asp-controller="Account" asp-action="Logout" method="post" id="logoutForm" class="navbar-right">
                <li class="dropdown link">
                    <a href="#" data-toggle="dropdown" class="dropdown-toggle profilebox"><img src="~/img/profileimg.png" alt="img"><b>@UserManager.GetUserName(User)</b><span class="caret"></span></a>

                    <ul class="dropdown-menu dropdown-menu-list dropdown-menu-right">
                        <li role="presentation" class="dropdown-header">Профіль</li>
                        <li><a href="#"><i class="fa falist fa-inbox"></i>Вхідні<span class="badge label-danger">4</span></a></li>
                        <li><a href="#"><i class="fa falist fa-file-o"></i>Файли</a></li>
                        <li><a href="#"><i class="fa falist fa-wrench"></i>Налаштування</a></li>
                        <li class="divider"></li>
                        <li><a href="#"><i class="fa falist fa-lock"></i> Екран блокування</a></li>
                        <li><button type="submit"><i class="fa falist fa-power-off"></i> Вихід</button></li>
                    </ul>
                </li>
            </form>

        </ul>
        <!-- Верхня права ч. кінець -->
    </div>
    <!-- Верхня ч. кінець -->
    <!-- //////////////////////////////////////////////////////////////////////////// -->
    <!-- //////////////////////////////////////////////////////////////////////////// -->
    <!-- Сайдбар початок -->
    <div class="sidebar clearfix sidebar-colorful">
        <ul class="sidebar-panel nav">
            <li>
                <a asp-action="index" asp-controller="rooms"><span class="icon color7"><i class="fa fa-bed"></i></span>Кімнати</a>
            </li>
            <li>
                <a asp-action="index" asp-controller="roomtypes"><span class="icon color2"><i class="fa fa-folder-open"></i></span>Категорії кімнат</a>
            </li>
            <li>
                <a asp-action="index" asp-controller="bookings"><span class="icon color3"><i class="fa fa-calendar"></i></span>Бронювання</a>

            </li>
            <li>
                <a asp-action="index" asp-controller="features"><span class="icon color7"><i class="fa fa-check-square-o"></i></span>Особливості</a>
            </li>
            <li><a href="#"><span class="icon color11"><i class="fa fa-diamond"></i></span>Відгуки</a></li>
            <li><a asp-action="index" asp-controller="images"><span class="icon color1"><i class="fa fa-image"></i></span>Медіа</a></li>
            <li>
                <a asp-action="index" asp-controller="manage"><span class="icon color10"><i class="fa fa-user"></i></span>Аккаунт</a>

            </li>
        </ul>
    </div>
    <!-- Сайдбар кінець -->
    <!-- //////////////////////////////////////////////////////////////////////////// -->
    <!-- //////////////////////////////////////////////////////////////////////////// -->
    <!-- Контент початок -->
    <div class="content">
        @RenderBody()
        <!-- END CONTAINER -->
        <!-- //////////////////////////////////////////////////////////////////////////// -->
        <!-- Футер початок -->
        <div class="row footer">
            <div class="col-md-6 text-left">
                Copyright © 2020 <a href="https://github.com/DDDigital/H-R-WS" target="_blank">H_R_WS.</a> Всі права захищені.
            </div>
            <div class="col-md-6 text-right">
                Створили та розробили студенти групи МІТ-41: <a href="https://github.com/DDDigital" target="_blank">Демченко А.В.</a>, <a href="https://github.com/invzbl3" target="_blank">Рогачов М.Д.</a>, <a href="https://github.com/connor999jobs" target="_blank">Костенко В.В.</a>, <a href="https://github.com/Elle85" target="_blank">Ізотов Д.І.</a>
            </div>
        </div>
        <!-- Футер кінець -->

    </div>
    <!-- Контент кінець -->
    <!-- //////////////////////////////////////////////////////////////////////////// -->
    <!-- //////////////////////////////////////////////////////////////////////////// -->
    <!-- Сайдпанель старт -->
    <!-- Сайдпанель кінець -->
    <!-- //////////////////////////////////////////////////////////////////////////// -->
    <!-- ================================================
    jQuery Library
    ================================================ -->
    <script type="text/javascript" src="~/js/jquery.min.js"></script>
    <!-- ================================================
    Bootstrap Core JavaScript File
    ================================================ -->
    <script src="~/js/bootstrap/bootstrap.min.js"></script>
    <!-- ================================================
    Plugin.js - Some Specific JS codes for Plugin Settings
    ================================================ -->
    <script type="text/javascript" src="~/js/plugins.js"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>